/**
 * S2: turn the dumped JSON fixtures into a TypeScript module core's tests can import
 * (core's tsconfig has `types: []` and no resolveJsonModule on purpose -- tests
 * cannot read files or import JSON, so the fixtures are embedded as constants, the
 * same way test/fixtures/real-transactions.ts is).
 *
 * Usage (from repo root):
 *   node spikes/02-reference-detection/fixtures-to-ts.mjs
 * Reads packages/core/test/fixtures/s2/*.json, writes packages/core/test/fixtures/s2/index.ts.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = 'packages/core/test/fixtures/s2';
const files = readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
const constName = (file) => 'S2_' + file.replace(/\.json$/, '').replace(/[^a-z0-9]+/gi, '_').toUpperCase();

let out = `/**
 * S2 devnet fixtures (spikes/02-reference-detection.md), fetched verbatim via
 * getTransaction (jsonParsed) from api.devnet.solana.com. Public chain data.
 * GENERATED by spikes/02-reference-detection/fixtures-to-ts.mjs from the JSON files
 * in this directory -- edit those and re-run, not this file.
 */
`;
for (const file of files) {
  const fixture = JSON.parse(readFileSync(join(dir, file), 'utf8'));
  out += `\nexport const ${constName(file)} = ${JSON.stringify(fixture, null, 2)} as const;\n`;
}
writeFileSync(join(dir, 'index.ts'), out);
console.log(`wrote ${join(dir, 'index.ts')} with ${files.map(constName).join(', ')}`);
