/**
 * S2 devnet fixtures (spikes/02-reference-detection.md), fetched verbatim via
 * getTransaction (jsonParsed) from api.devnet.solana.com. Public chain data.
 * GENERATED by spikes/02-reference-detection/fixtures-to-ts.mjs from the JSON files
 * in this directory -- edit those and re-run, not this file.
 */

export const S2_A_FIRST_QR_PAYMENT_ATA_CREATE = {
  "signature": "2hxU3WUdQHCDTELUtP2nyUfPUEMeAvCKmGnXHBkPem9rLmwh7YTAdcL6ZGLLj5thWUZ3UehHm9A1rDj9oneS4kaP",
  "slot": 498730500,
  "blockTime": 1789469402,
  "raw": {
    "blockTime": 1789469402,
    "meta": {
      "computeUnitsConsumed": 15604,
      "costUnits": 17285,
      "err": null,
      "fee": 325000,
      "innerInstructions": [
        {
          "index": 2,
          "instructions": [
            {
              "parsed": {
                "info": {
                  "extensionTypes": [
                    "immutableOwner"
                  ],
                  "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
                },
                "type": "getAccountDataSize"
              },
              "program": "spl-token",
              "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
              "stackHeight": 2
            },
            {
              "parsed": {
                "info": {
                  "lamports": 1488440,
                  "newAccount": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
                  "owner": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
                  "source": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
                  "space": 165
                },
                "type": "createAccount"
              },
              "program": "system",
              "programId": "11111111111111111111111111111111",
              "stackHeight": 2
            },
            {
              "parsed": {
                "info": {
                  "account": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk"
                },
                "type": "initializeImmutableOwner"
              },
              "program": "spl-token",
              "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
              "stackHeight": 2
            },
            {
              "parsed": {
                "info": {
                  "account": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
                  "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
                  "owner": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy"
                },
                "type": "initializeAccount3"
              },
              "program": "spl-token",
              "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
              "stackHeight": 2
            }
          ]
        }
      ],
      "logMessages": [
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]",
        "Program log: Create",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 179 of 392662 compute units",
        "Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Initialize the associated token account",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 37 of 387573 compute units",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 233 of 385110 compute units",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
        "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 15161 of 399700 compute units",
        "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 143 of 384539 compute units",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
      ],
      "postBalances": [
        5498186560,
        1488440,
        1488440,
        1,
        0,
        418423285289,
        1,
        20367267856,
        1009200,
        5938070540,
        0
      ],
      "postTokenBalances": [
        {
          "accountIndex": 1,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "1000000",
            "decimals": 6,
            "uiAmount": 1,
            "uiAmountString": "1"
          }
        },
        {
          "accountIndex": 2,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "19000000",
            "decimals": 6,
            "uiAmount": 19,
            "uiAmountString": "19"
          }
        }
      ],
      "preBalances": [
        5500000000,
        0,
        1488440,
        1,
        0,
        418423285289,
        1,
        20367267856,
        1009200,
        5938070540,
        0
      ],
      "preTokenBalances": [
        {
          "accountIndex": 2,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "20000000",
            "decimals": 6,
            "uiAmount": 20,
            "uiAmountString": "20"
          }
        }
      ],
      "rewards": [],
      "status": {
        "Ok": null
      }
    },
    "slot": 498730500,
    "transaction": {
      "message": {
        "accountKeys": [
          {
            "pubkey": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
            "signer": true,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
            "signer": false,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "3VzL3GqnRkBsigQAATjrsmhgEEZHhYXa28G5eTJZRnCA",
            "signer": false,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "ComputeBudget111111111111111111111111111111",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "11111111111111111111111111111111",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "SysvarRent111111111111111111111111111111111",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "E1NcgdMEVzBLbuPvdNarARrCsdhn4gcF5HD9ViYUoBq9",
            "signer": false,
            "source": "transaction",
            "writable": false
          }
        ],
        "instructions": [
          {
            "accounts": [],
            "data": "3DVaC8fPXTwD",
            "programId": "ComputeBudget111111111111111111111111111111",
            "stackHeight": 1
          },
          {
            "accounts": [],
            "data": "HMypLP",
            "programId": "ComputeBudget111111111111111111111111111111",
            "stackHeight": 1
          },
          {
            "parsed": {
              "info": {
                "account": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
                "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
                "source": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
                "systemProgram": "11111111111111111111111111111111",
                "tokenProgram": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
                "wallet": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy"
              },
              "type": "create"
            },
            "program": "spl-associated-token-account",
            "programId": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
            "stackHeight": 1
          },
          {
            "parsed": {
              "info": {
                "amount": "1000000",
                "destination": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
                "multisigAuthority": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
                "signers": [
                  "E1NcgdMEVzBLbuPvdNarARrCsdhn4gcF5HD9ViYUoBq9"
                ],
                "source": "3VzL3GqnRkBsigQAATjrsmhgEEZHhYXa28G5eTJZRnCA"
              },
              "type": "transfer"
            },
            "program": "spl-token",
            "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "stackHeight": 1
          }
        ],
        "recentBlockhash": "BBtsKMYLJFDkGFvkDPGuUGLW3kpcWnnAJq2b97JmPnyE"
      },
      "signatures": [
        "2hxU3WUdQHCDTELUtP2nyUfPUEMeAvCKmGnXHBkPem9rLmwh7YTAdcL6ZGLLj5thWUZ3UehHm9A1rDj9oneS4kaP"
      ]
    },
    "transactionIndex": 32,
    "version": "legacy"
  }
} as const;

export const S2_A2_QR_PAYMENT = {
  "signature": "2VhXYszgjKAGMRyU5B9j1sxYCvF2yfttBAveeVFL5WMDBCtPwiYG8mq4QRCWfF754TwRAXDkpKcwLinxwqDaipx4",
  "slot": 498776468,
  "blockTime": 1789476953,
  "raw": {
    "blockTime": 1789476953,
    "meta": {
      "computeUnitsConsumed": 443,
      "costUnits": 2100,
      "err": null,
      "fee": 165000,
      "innerInstructions": [],
      "logMessages": [
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 143 of 199700 compute units",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
      ],
      "postBalances": [
        5498021560,
        1488440,
        1488440,
        1,
        0,
        20367267856
      ],
      "postTokenBalances": [
        {
          "accountIndex": 1,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "18000000",
            "decimals": 6,
            "uiAmount": 18,
            "uiAmountString": "18"
          }
        },
        {
          "accountIndex": 2,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "2000000",
            "decimals": 6,
            "uiAmount": 2,
            "uiAmountString": "2"
          }
        }
      ],
      "preBalances": [
        5498186560,
        1488440,
        1488440,
        1,
        0,
        20367267856
      ],
      "preTokenBalances": [
        {
          "accountIndex": 1,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "19000000",
            "decimals": 6,
            "uiAmount": 19,
            "uiAmountString": "19"
          }
        },
        {
          "accountIndex": 2,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "1000000",
            "decimals": 6,
            "uiAmount": 1,
            "uiAmountString": "1"
          }
        }
      ],
      "rewards": [],
      "status": {
        "Ok": null
      }
    },
    "slot": 498776468,
    "transaction": {
      "message": {
        "accountKeys": [
          {
            "pubkey": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
            "signer": true,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "3VzL3GqnRkBsigQAATjrsmhgEEZHhYXa28G5eTJZRnCA",
            "signer": false,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
            "signer": false,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "ComputeBudget111111111111111111111111111111",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "2vhyWoqeYsEoDyuFBBWx3fEyn1b8NGeryrwbMmW55tSR",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "signer": false,
            "source": "transaction",
            "writable": false
          }
        ],
        "instructions": [
          {
            "accounts": [],
            "data": "3DVaC8fPXTwD",
            "programId": "ComputeBudget111111111111111111111111111111",
            "stackHeight": 1
          },
          {
            "accounts": [],
            "data": "Fj2Eoy",
            "programId": "ComputeBudget111111111111111111111111111111",
            "stackHeight": 1
          },
          {
            "parsed": {
              "info": {
                "amount": "1000000",
                "destination": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
                "multisigAuthority": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
                "signers": [
                  "2vhyWoqeYsEoDyuFBBWx3fEyn1b8NGeryrwbMmW55tSR"
                ],
                "source": "3VzL3GqnRkBsigQAATjrsmhgEEZHhYXa28G5eTJZRnCA"
              },
              "type": "transfer"
            },
            "program": "spl-token",
            "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "stackHeight": 1
          }
        ],
        "recentBlockhash": "DZnvC7UQks8i1FyPeQArraeJptvDDcFK8djNseNe5ZiZ"
      },
      "signatures": [
        "2VhXYszgjKAGMRyU5B9j1sxYCvF2yfttBAveeVFL5WMDBCtPwiYG8mq4QRCWfF754TwRAXDkpKcwLinxwqDaipx4"
      ]
    },
    "transactionIndex": 24,
    "version": "legacy"
  }
} as const;

export const S2_B_SECOND_QR_PAYMENT = {
  "signature": "N3VcTqQaRMQNQ9hvuzHE37JMdtZT6vG1BEwHnM6MFoPTtrW4ZNR4fBR45owagQ1PHq2znLg5Ynk7UpUgEJGJRWZ",
  "slot": 498777017,
  "blockTime": 1789477043,
  "raw": {
    "blockTime": 1789477043,
    "meta": {
      "computeUnitsConsumed": 443,
      "costUnits": 2100,
      "err": null,
      "fee": 165000,
      "innerInstructions": [],
      "logMessages": [
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 143 of 199700 compute units",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
      ],
      "postBalances": [
        5497856560,
        1488440,
        1488440,
        1,
        0,
        20367267856
      ],
      "postTokenBalances": [
        {
          "accountIndex": 1,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "16000000",
            "decimals": 6,
            "uiAmount": 16,
            "uiAmountString": "16"
          }
        },
        {
          "accountIndex": 2,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "4000000",
            "decimals": 6,
            "uiAmount": 4,
            "uiAmountString": "4"
          }
        }
      ],
      "preBalances": [
        5498021560,
        1488440,
        1488440,
        1,
        0,
        20367267856
      ],
      "preTokenBalances": [
        {
          "accountIndex": 1,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "18000000",
            "decimals": 6,
            "uiAmount": 18,
            "uiAmountString": "18"
          }
        },
        {
          "accountIndex": 2,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "2000000",
            "decimals": 6,
            "uiAmount": 2,
            "uiAmountString": "2"
          }
        }
      ],
      "rewards": [],
      "status": {
        "Ok": null
      }
    },
    "slot": 498777017,
    "transaction": {
      "message": {
        "accountKeys": [
          {
            "pubkey": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
            "signer": true,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "3VzL3GqnRkBsigQAATjrsmhgEEZHhYXa28G5eTJZRnCA",
            "signer": false,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
            "signer": false,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "ComputeBudget111111111111111111111111111111",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "HopAmorzvr66NvpUmWcb3ShBxTMiFcDkjSr1s4b9V3U6",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "signer": false,
            "source": "transaction",
            "writable": false
          }
        ],
        "instructions": [
          {
            "accounts": [],
            "data": "3DVaC8fPXTwD",
            "programId": "ComputeBudget111111111111111111111111111111",
            "stackHeight": 1
          },
          {
            "accounts": [],
            "data": "Fj2Eoy",
            "programId": "ComputeBudget111111111111111111111111111111",
            "stackHeight": 1
          },
          {
            "parsed": {
              "info": {
                "amount": "2000000",
                "destination": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
                "multisigAuthority": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
                "signers": [
                  "HopAmorzvr66NvpUmWcb3ShBxTMiFcDkjSr1s4b9V3U6"
                ],
                "source": "3VzL3GqnRkBsigQAATjrsmhgEEZHhYXa28G5eTJZRnCA"
              },
              "type": "transfer"
            },
            "program": "spl-token",
            "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "stackHeight": 1
          }
        ],
        "recentBlockhash": "5ngYxF2vCyyWuzb8rxBuXmjkXKYJ3FFRWRq8Sp5qbGkC"
      },
      "signatures": [
        "N3VcTqQaRMQNQ9hvuzHE37JMdtZT6vG1BEwHnM6MFoPTtrW4ZNR4fBR45owagQ1PHq2znLg5Ynk7UpUgEJGJRWZ"
      ]
    },
    "transactionIndex": 0,
    "version": "legacy"
  }
} as const;

export const S2_C_DIRECT_TRANSFER = {
  "signature": "mXKWyLB8CnHneFWYFvHd5zajdwAk8sBTRyzb9FbynbZHSdjPasBGCVX5eBivxxc8Ywx3nZBJFCu4ZGh9quNmjin",
  "slot": 498777644,
  "blockTime": 1789477146,
  "raw": {
    "blockTime": 1789477146,
    "meta": {
      "computeUnitsConsumed": 405,
      "costUnits": 2063,
      "err": null,
      "fee": 5333,
      "innerInstructions": [],
      "logMessages": [
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 105 of 116 compute units",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success"
      ],
      "postBalances": [
        5497851227,
        1488440,
        1488440,
        418423285289,
        1,
        20367267856
      ],
      "postTokenBalances": [
        {
          "accountIndex": 1,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "13000000",
            "decimals": 6,
            "uiAmount": 13,
            "uiAmountString": "13"
          }
        },
        {
          "accountIndex": 2,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "7000000",
            "decimals": 6,
            "uiAmount": 7,
            "uiAmountString": "7"
          }
        }
      ],
      "preBalances": [
        5497856560,
        1488440,
        1488440,
        418423285289,
        1,
        20367267856
      ],
      "preTokenBalances": [
        {
          "accountIndex": 1,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "16000000",
            "decimals": 6,
            "uiAmount": 16,
            "uiAmountString": "16"
          }
        },
        {
          "accountIndex": 2,
          "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
          "owner": "EFhBHyksYoBLSQSa71N1wMZ7cNyP2x68XtFr1uaMRjEy",
          "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
          "uiTokenAmount": {
            "amount": "4000000",
            "decimals": 6,
            "uiAmount": 4,
            "uiAmountString": "4"
          }
        }
      ],
      "rewards": [],
      "status": {
        "Ok": null
      }
    },
    "slot": 498777644,
    "transaction": {
      "message": {
        "accountKeys": [
          {
            "pubkey": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
            "signer": true,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "3VzL3GqnRkBsigQAATjrsmhgEEZHhYXa28G5eTJZRnCA",
            "signer": false,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
            "signer": false,
            "source": "transaction",
            "writable": true
          },
          {
            "pubkey": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "ComputeBudget111111111111111111111111111111",
            "signer": false,
            "source": "transaction",
            "writable": false
          },
          {
            "pubkey": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "signer": false,
            "source": "transaction",
            "writable": false
          }
        ],
        "instructions": [
          {
            "accounts": [],
            "data": "3DVaC8fPXTwD",
            "programId": "ComputeBudget111111111111111111111111111111",
            "stackHeight": 1
          },
          {
            "accounts": [],
            "data": "JBH1rf",
            "programId": "ComputeBudget111111111111111111111111111111",
            "stackHeight": 1
          },
          {
            "parsed": {
              "info": {
                "authority": "CuxRzb13MUpQyk8riEGgJwE16jXRDFuYptQN67P3dkmY",
                "destination": "9Qo8ErTa2nHujJwM1GppBoCb2v6tGvzcH1UMcuYaYBgk",
                "mint": "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
                "source": "3VzL3GqnRkBsigQAATjrsmhgEEZHhYXa28G5eTJZRnCA",
                "tokenAmount": {
                  "amount": "3000000",
                  "decimals": 6,
                  "uiAmount": 3,
                  "uiAmountString": "3"
                }
              },
              "type": "transferChecked"
            },
            "program": "spl-token",
            "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
            "stackHeight": 1
          }
        ],
        "recentBlockhash": "4pPzrVbxySvwWZdRNXJtqxcgn38x3aZ6toeawTnGvQN7"
      },
      "signatures": [
        "mXKWyLB8CnHneFWYFvHd5zajdwAk8sBTRyzb9FbynbZHSdjPasBGCVX5eBivxxc8Ywx3nZBJFCu4ZGh9quNmjin"
      ]
    },
    "transactionIndex": 15,
    "version": "legacy"
  }
} as const;
