/**
 * Expo config plugin: real release signing for the Android build (T17/T33).
 *
 * Expo's generated android/app/build.gradle signs the `release` build type with the
 * DEBUG keystore, and `android/` is gitignored and regenerated by `expo prebuild`,
 * so a hand edit there would not survive. This plugin patches the file at prebuild
 * time instead: it adds a `release` signing config that reads the keystore path and
 * passwords from Gradle properties, and points the release build type at it.
 *
 * The secrets never enter the repo. Put them in ~/.gradle/gradle.properties on the
 * build machine:
 *
 *   LOCAL_BOOKS_RELEASE_STORE_FILE=/Users/you/.local-books/release.keystore
 *   LOCAL_BOOKS_RELEASE_STORE_PASSWORD=...
 *   LOCAL_BOOKS_RELEASE_KEY_ALIAS=localbooks
 *   LOCAL_BOOKS_RELEASE_KEY_PASSWORD=...
 *
 * Without them the release build type has NO signing config: Gradle emits
 * `app-release-unsigned.apk`, which cannot be installed and says why in its name. A
 * debug-signed "release" would install fine and could never be updated in place by
 * the real key -- and in this app the uninstall that fixes that deletes the
 * encrypted books -- so the fallback is loud on purpose. A local smoke build may
 * opt back into the debug key with `-PLOCAL_BOOKS_ALLOW_DEBUG_SIGNED_RELEASE=true`.
 * The build log prints which key was used (see the `println` below).
 *
 * Plain CommonJS on purpose: Expo loads config plugins with require() at prebuild
 * time, outside Metro and outside the TypeScript build.
 */
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = 'LOCAL_BOOKS_RELEASE_STORE_FILE';

const RELEASE_SIGNING_CONFIG = `        release {
            // Local Books (plugins/withReleaseSigning.js): keystore + passwords come
            // from ~/.gradle/gradle.properties on the build machine, never the repo.
            if (project.hasProperty('${MARKER}')) {
                storeFile file(LOCAL_BOOKS_RELEASE_STORE_FILE)
                storePassword LOCAL_BOOKS_RELEASE_STORE_PASSWORD
                keyAlias LOCAL_BOOKS_RELEASE_KEY_ALIAS
                keyPassword LOCAL_BOOKS_RELEASE_KEY_PASSWORD
            }
        }
`;

const ALLOW_DEBUG = 'LOCAL_BOOKS_ALLOW_DEBUG_SIGNED_RELEASE';

// Parenthesised on purpose: Groovy ends a statement at a newline unless the
// expression is visibly open, so a bare multi-line ternary would not parse.
const RELEASE_SIGNING_CONFIG_USE = `            signingConfig = (project.hasProperty('${MARKER}')
                ? signingConfigs.release
                : (project.hasProperty('${ALLOW_DEBUG}') ? signingConfigs.debug : null))
            println(project.hasProperty('${MARKER}')
                ? "Local Books: release build signed with the RELEASE keystore"
                : (project.hasProperty('${ALLOW_DEBUG}')
                    ? "Local Books: release build signed with the DEBUG keystore (${ALLOW_DEBUG} set) -- never publish this APK"
                    : "Local Books: NO release keystore (${MARKER} missing from gradle.properties) -- producing app-release-unsigned.apk, which cannot be installed"))`;

/**
 * Pure, idempotent text patch so it can be unit-tested without Expo. Throws when
 * the template no longer looks like the one this was written against, because a
 * silent no-op here would ship a debug-signed "release".
 */
function patchBuildGradle(contents) {
  if (contents.includes(MARKER)) return contents;

  const debugConfig = /(    signingConfigs \{\n        debug \{\n(?:            .*\n)+?        \}\n)/;
  if (!debugConfig.test(contents)) {
    throw new Error('withReleaseSigning: signingConfigs.debug block not found in app/build.gradle');
  }
  let out = contents.replace(debugConfig, `$1${RELEASE_SIGNING_CONFIG}`);

  const releaseUsesDebug =
    /(        release \{\n(?:            \/\/.*\n)*)            signingConfig signingConfigs\.debug\n/;
  if (!releaseUsesDebug.test(out)) {
    throw new Error('withReleaseSigning: buildTypes.release signingConfig line not found in app/build.gradle');
  }
  out = out.replace(releaseUsesDebug, `$1${RELEASE_SIGNING_CONFIG_USE}\n`);
  return out;
}

const withReleaseSigning = (config) =>
  withAppBuildGradle(config, (mod) => {
    if (mod.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning: expected a Groovy app/build.gradle');
    }
    mod.modResults.contents = patchBuildGradle(mod.modResults.contents);
    return mod;
  });

module.exports = withReleaseSigning;
module.exports.patchBuildGradle = patchBuildGradle;
